export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACE_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!;
export const ISSUES_ID = process.env.NEXT_PUBLIC_APPWRITE_ISSUES_ID!;
export const ROOMS_ID = process.env.NEXT_PUBLIC_APPWRITE_ROOMS_ID!;
export const IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
export const MESSAGE_ID = process.env.NEXT_PUBLIC_APPWRITE_MESSAGES_ID!;
export const PR_ID = process.env.NEXT_PUBLIC_APPWRITE_PR_ID!;
export const NOTIFICATIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_NOTIFICATIONS_ID!;
export const COMMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_COMMENTS_ID!;
export const AI_TESTS_ID = process.env.NEXT_PUBLIC_APPWRITE_AI_TESTS_ID!;
export const USER_PROFILES_ID = process.env.NEXT_PUBLIC_APPWRITE_USER_PROFILES_ID!;
export const SUBSCRIPTIONS_ID = process.env.NEXT_PUBLIC_APPWRITE_SUBSCRIPTIONS_ID!;
export const USER_USAGE_ID = process.env.NEXT_PUBLIC_APPWRITE_USER_USAGE_ID!;
export const GEMINI_API_KEY = process.env.GEMINI_API_KEY!;